name: Android CI Run
on: workflow_dispatch
jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Appium
      run: |
        npm install -g appium@v2.6.0
        appium -v
        appium &>/dev/null &

    - name: Run Android Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: mvn clean test