name: iOS workflow
on: workflow_dispatch

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    strategy:
      matrix:
        device: [ "iPhone 12", "iPhone 12 Pro", "iPhone 12 Pro Max" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Appium
        run: |
          npm install -g appium@2.6.0
          npm install @appium/doctor -g
          npm install -g appium-webdriveragent
          appium driver install xcuitest
          appium driver list --installed
          appium-doctor --ios

      - name: Start Appium server
        run: |
          nohup appium &

      - name: Wait for Appium server to start
        run: sleep 15

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "${{ matrix.device }}"
          xcrun simctl bootstatus "${{ matrix.device }}" -b

      - name: Run iOS Tests
        run: |
          mvn clean test
