name: iOS workflow
on: workflow_dispatch

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Appium
        run: |
          npm install -g appium@2.6.0
          npm install @appium/doctor -g
          npm install -g appium-webdriveragent
          appium driver install xcuitest
          appium driver list --installed
          appium-doctor --ios

      - name: Start Appium server
        run: |
          nohup appium &

      - name: Wait for Appium server to start
        run: sleep 15

      - name: Run iOS Tests
        run: |
          mvn clean test
